site_name: Explaining Israel
site_url: https://explain-israel.info/
theme:
  name: material
  logo: Assets/logo.png
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Home: index.md
  - General:
    - General/The battle for the truth.md
    - General/Propaganda-Tactics.md
    - General/Social Network Resources.md
  - Specific Topics:
    - Specific Topics/Education.md
    - Specific Topics/The indigineous People.md
    - Specific Topics/Who Owns The Land.md
    - Specific Topics/The Palestinians welcomed the Jews.md
    - Specific Topics/Jews stole the land.md

